# Generated by Django 5.1.3 on 2024-11-30 22:50

import app.models
import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_currency_alter_user_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='month',
            name='review',
            field=djongo.models.fields.EmbeddedField(blank=True, model_container=app.models.Review),
        ),
        migrations.AlterField(
            model_name='month',
            name='weeks',
            field=djongo.models.fields.ArrayField(blank=True, model_container=app.models.Week),
        ),
    ]
