# Generated by Django 5.1.3 on 2024-11-30 22:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_month_id_alter_month_review_alter_month_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
